# Generated by Django 5.1.2 on 2024-11-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Unknown', max_length=30)),
                ('last_name', models.CharField(default='Unknown', max_length=30)),
                ('age', models.PositiveIntegerField(default=18)),
                ('Specialization', models.CharField(default='Unknown', max_length=50)),
                ('image', models.ImageField(null=True, upload_to='images/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
